[versions]
agp = "9.4.0"
kotlin = "2.4.20"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.10.0" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.11.0" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version = "2.2.21-1.10.3" }
